"""
gen_version.py — PlatformIO extra_script (pre-build)
Writes include/core/fw_version_gen.h with the current build version and a
per-build Unix timestamp.

FW_VERSION  : vYY.MM.##  (year, month, build counter within that month)
FW_BUILD_TS : Unix timestamp of this build (seconds since epoch, uint32_t)

The ## counter increments on every build and resets to 01 when the
year/month rolls over. There is no separate state file — the counter is
recovered by parsing the previously committed fw_version_gen.h, the same
"committed fallback" file this script overwrites every build. If that file
is missing or unparsable, the counter restarts at 01.

FW_BUILD_TS changes on every build → fw_version_gen.h always changes →
settings_manager.cpp always recompiles → FW_STAMP_VAL is unique per build.
This guarantees a stamp mismatch after any USB or OTA firmware update,
so the device always boots to radar mode on first boot after reflash.

Generating a header file is more reliable than env.Append(CPPDEFINES)
for ESP-IDF/CMake builds, where SCons flags may not propagate to CMake.

FW_VERSION_OVERRIDE (env var, unset for normal/local builds): the release
workflow sets this to the exact git tag it's building, so the embedded
FW_VERSION always matches the tag precisely instead of drifting ahead of
it by however many local builds happened first that month (see
docs/firmware_installation.md's versioning-mismatch note — this is the
fix for it). Must match vYY.MM.## or the build fails loudly rather than
silently falling back to the counter.
"""
Import("env")
import datetime
import re
import time
import os

d = datetime.datetime.now()
year, month = d.year % 100, d.month

header_path = os.path.join(
    env["PROJECT_DIR"], "include", "core", "fw_version_gen.h"
)

override = os.environ.get("FW_VERSION_OVERRIDE", "").strip()
if override:
    if not re.fullmatch(r"v\d{2}\.\d{2}\.\d+", override):
        raise ValueError(
            "FW_VERSION_OVERRIDE={!r} doesn't match vYY.MM.## — refusing to "
            "embed a malformed release version.".format(override)
        )
    version = override
else:
    counter = 1
    try:
        with open(header_path) as f:
            prev = f.read()
        m = re.search(r'FW_VERSION "v(\d{2})\.(\d{2})\.(\d+)"', prev)
        if m and int(m.group(1)) == year and int(m.group(2)) == month:
            counter = int(m.group(3)) + 1
    except OSError:
        pass
    version = "v{:02d}.{:02d}.{:02d}".format(year, month, counter)

build_ts = int(time.time())

with open(header_path, "w") as f:
    f.write("// Auto-generated by scripts/gen_version.py — do not edit\n")
    f.write("// Regenerated on every build. Committed fallback exists for IDEs.\n")
    f.write("#pragma once\n")
    f.write('#undef  FW_VERSION\n')
    f.write('#define FW_VERSION "{}"\n'.format(version))
    f.write('#undef  FW_BUILD_TS\n')
    f.write('#define FW_BUILD_TS {}u\n'.format(build_ts))

print("[VERSION] FW_VERSION = {}  FW_BUILD_TS = {}  →  {}".format(version, build_ts, header_path))
