"""
gen_version.py — PlatformIO extra_script (pre-build)
Writes include/core/fw_version_gen.h with the current build date and a
per-build Unix timestamp.

FW_VERSION  : vYY.MM.DD  (CalVer, display-safe)
FW_BUILD_TS : Unix timestamp of this build (seconds since epoch, uint32_t)

FW_BUILD_TS changes on every build → fw_version_gen.h always changes →
settings_manager.cpp always recompiles → FW_STAMP_VAL is unique per build.
This guarantees a stamp mismatch after any USB or OTA firmware update,
so the device always boots to radar mode on first boot after reflash.

Generating a header file is more reliable than env.Append(CPPDEFINES)
for ESP-IDF/CMake builds, where SCons flags may not propagate to CMake.
"""
Import("env")
import datetime
import time
import os

d = datetime.datetime.now()
version = "v{:02d}.{:02d}.{:02d}".format(d.year % 100, d.month, d.day)
build_ts = int(time.time())

header_path = os.path.join(
    env["PROJECT_DIR"], "include", "core", "fw_version_gen.h"
)

with open(header_path, "w") as f:
    f.write("// Auto-generated by scripts/gen_version.py — do not edit\n")
    f.write("// Regenerated on every build. Committed fallback exists for IDEs.\n")
    f.write("#pragma once\n")
    f.write('#undef  FW_VERSION\n')
    f.write('#define FW_VERSION "{}"\n'.format(version))
    f.write('#undef  FW_BUILD_TS\n')
    f.write('#define FW_BUILD_TS {}u\n'.format(build_ts))

print("[VERSION] FW_VERSION = {}  FW_BUILD_TS = {}  →  {}".format(version, build_ts, header_path))
